# Generated by Django 2.1.11 on 2020-05-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveDataApp', '0003_counter_count1'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests', models.IntegerField()),
                ('when', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
