# Generated by Django 3.0.4 on 2020-04-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dailyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName', models.CharField(max_length=50)),
                ('confirmedCases', models.CharField(max_length=50)),
                ('curedCases', models.CharField(max_length=50)),
                ('deathCases', models.CharField(max_length=50)),
                ('when', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
