# Generated by Django 2.1.11 on 2020-04-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveDataApp', '0002_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='count1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
